task: detection

num_classes: 10
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
#    img_folder: ./src/data/coco/train2017/
    img_folder: ../rtdetr_pytorch/src/data/visdrone/VisDrone2019-DET-train
#    img_folder: ./src/data/dior/trainval/
#    ann_file: ./src/data/coco/annotations/instances_train2017.json
    ann_file: ../rtdetr_pytorch/src/data/visdrone/train.json
#    ann_file: ./src/data/dior/train.json
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  batch_size: 4
  num_workers: 4
  drop_last: True 


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
#    img_folder: ./src/data/coco/val2017/
    img_folder: ../rtdetr_pytorch/src/data/visdrone/VisDrone2019-DET-val
#    img_folder: ./src/data/dior/trainval/
#    ann_file: ./src/data/coco/annotations/instances_val2017.json
    ann_file: ../rtdetr_pytorch/src/data/visdrone/val.json
#    ann_file: ./src/data/dior/val.json
    transforms:
      type: Compose
      ops: ~ 

  shuffle: False
  batch_size: 4
  num_workers: 4
  drop_last: False